# Generated by Django 5.1.2 on 2024-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fly_id", models.CharField(max_length=50, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "segmented_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="segmented_images/"
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="original_images/"
                    ),
                ),
                (
                    "area_2P",
                    models.FloatField(help_text="Area for 2P in square micrometers"),
                ),
                (
                    "area_C",
                    models.FloatField(help_text="Area for C in square micrometers"),
                ),
                (
                    "area_M",
                    models.FloatField(help_text="Area for M in square micrometers"),
                ),
                (
                    "area_S",
                    models.FloatField(help_text="Area for S in square micrometers"),
                ),
                (
                    "area_D",
                    models.FloatField(help_text="Area for D in square micrometers"),
                ),
                (
                    "area_1P",
                    models.FloatField(help_text="Area for 1P in square micrometers"),
                ),
                (
                    "area_B1",
                    models.FloatField(help_text="Area for B1 in square micrometers"),
                ),
            ],
        ),
    ]
