# Generated by Django 5.1.2 on 2024-12-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wing_segmentation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wing",
            name="area_C",
        ),
        migrations.AddField(
            model_name="wing",
            name="area_3P",
            field=models.FloatField(
                default=0, help_text="Area for 3P in square micrometers"
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="area_1P",
            field=models.FloatField(
                default=0, help_text="Area for 1P in square micrometers"
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="area_2P",
            field=models.FloatField(
                default=0, help_text="Area for 2P in square micrometers"
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="area_B1",
            field=models.FloatField(
                default=0, help_text="Area for B1 in square micrometers"
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="area_D",
            field=models.FloatField(
                default=0, help_text="Area for D in square micrometers"
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="area_M",
            field=models.FloatField(
                default=0, help_text="Area for M in square micrometers"
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="area_S",
            field=models.FloatField(
                default=0, help_text="Area for S in square micrometers"
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="original_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="wing_segmentation/static/images/original_images/",
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="segmented_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="wing_segmentation/static/images/segmented_images/",
            ),
        ),
    ]
