# Generated by Django 5.1.2 on 2025-04-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gender",
            name="hog",
            field=models.ImageField(default=1, upload_to="gender/hog/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gender",
            name="image",
            field=models.ImageField(null=True, upload_to="gender/original/"),
        ),
    ]
